apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

---
kind: Service
apiVersion: v1
metadata:
  name: plex
spec:
  selector:
    app: plex
  ports:
    - port: 80
      targetPort: 32400

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      name: plex
      labels:
        app: plex
    spec:
      containers:
        - name: plex
          image: plexinc/pms-docker
          env:
            - name: PLEX_UID
              value: "1000"
            - name: PLEX_GID
              value: "1000"
            - name: TZ
              value: "Europe/Stockholm"
          ports:
            - containerPort: 32400
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: plex-config
        - name: media
          nfs:
            server: "10.1.40.100"
            path: /mnt/tank/media
