kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-delete
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  fromBackup: ""
  fsType: "ext4"

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-retain
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  fromBackup: ""
  fsType: "ext4"
