apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.4.2
    chart: ingress-nginx
    helm:
      parameters:
      - name: "controller.ingressClassResource.default"
        value: "true"
  destination:
    namespace: ingress-nginx
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
