apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.23.0
    chart: vault
    helm:
      values: |
        global:
          externalVaultAddr: 'https://vault.arleskog.se'
        injector:
          authPath: "auth/priv-k3s"
  destination:
    namespace: vault
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
