apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi

---
kind: Service
apiVersion: v1
metadata:
  name: prowlarr
spec:
  selector:
    app: prowlarr
  ports:
    - port: 80
      targetPort: 9696

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      name: prowlarr
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Stockholm"
          ports:
            - containerPort: 9696
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 9696
            initialDelaySeconds: 180
            periodSeconds: 60
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config
      # Trackers does not resolve otherwise.
      # https://stackoverflow.com/questions/65181012/does-alpine-have-known-dns-issue-within-kubernetes
      dnsConfig:
        options:
          - name: ndots
            value: "1"
