apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi

---
kind: Service
apiVersion: v1
metadata:
  name: bazarr
spec:
  selector:
    app: bazarr
  ports:
    - port: 80
      targetPort: 6767

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      name: bazarr
      labels:
        app: bazarr
    spec:
      containers:
        - name: bazarr
          image: lscr.io/linuxserver/bazarr
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Stockholm"
          ports:
            - containerPort: 6767
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /
              port: 6767
            initialDelaySeconds: 60
            periodSeconds: 60
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: bazarr-config
        - name: media
          nfs:
            server: "10.1.40.6"
            path: /mnt/pve/media
      dnsConfig:
        options:
          - name: ndots
            value: "1"
