apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-mullvad-vpn
  namespace: servarr
spec:
  selector: app == 'qbittorrent'
  ingress:
  - action: Allow
    protocol: UDP
    source:
      nets:
        - 10.50.0.0/16
  egress:
  - action: Allow
    protocol: UDP
    destination:
      nets:
        - 185.213.154.69/32
      ports:
        - 51820
  - action: Allow
    protocol: TCP
    source:
      namespaceSelector: kubernetes.io/metadata.name == 'servarr'
  - action: Allow
    protocol: UDP
    destination:
      nets:
        - 10.50.0.0/16
      ports:
        - 53

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-retain
  resources:
    requests:
      storage: 512Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-retain
  resources:
    requests:
      storage: 512Mi

---
kind: Service
apiVersion: v1
metadata:
  name: qbittorrent
spec:
  selector:
    app: qbittorrent
  ports:
    - port: 80
      targetPort: 8080

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      name: qbittorrent
      labels:
        app: qbittorrent
    spec:
      containers:
        - name: wireguard
          image: lscr.io/linuxserver/wireguard
          env:
            - name: INTERNAL_SUBNET
              value: "10.50.0.0/24"
          volumeMounts:
            - name: wireguard
              mountPath: /config
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            sysctls:
              - name: net.ipv4.conf.all.src_valid_mark
                value: "1"
        - name: qbittorrent
          image: hotio/qbittorrent:release
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Stockholm"
            - name: UMASK
              value: "002"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: wg0.conf
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
      volumes:
        - name: wireguard
          persistentVolumeClaim:
            claimName: wireguard-config
            optional: false
        - name: config
          persistentVolumeClaim:
            claimName: qbittorrent-config
