apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.13.7
    chart: metallb
  destination:
    namespace: metallb-system
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true

---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: cheap-ipv4
  namespace: metallb-system
spec:
  addresses:
  - 10.1.40.40-10.1.40.80
